export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAIL = 'GET_EXERCISES_FAIL';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';